version: '3.8'

services:

  mongo:
    image: mongo
    restart: always
    ports: 
      - 27017:27017
    networks:
      - epl
    volumes: 
      - mongo-storage:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    networks:
      - epl
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_ROOT_USER}:${MONGO_ROOT_PASSWORD}@mongo:27017/
    depends_on:
      - mongo
      
  football:
    build: .
    command: sh -c "cd football && python premier.py"
    volumes:
      - .:/app
    networks:
      - epl
    depends_on:
      - mongo

  fastapi:
    build: .
    command: sh -c "cd app && python main.py"
    restart: always
    volumes:
      - .:/app
    ports:
      - 8001:8000
    networks:
      - epl
    expose:
      - 8001
    depends_on:
      - mongo


# volume 설정.
volumes:
  mongo-storage:
# networks 
networks:
  epl:
    driver: bridge
